(import pyffi)

(py-start)
(py-eval "print(open)")
(py-import "sys")
(assert (string? (py-eval "sys.version")))
(print "Python version: " (py-eval "sys.version"))
(print (py-eval "1"))
(print (py-eval "1.0"))
(print (py-eval "float('-inf')"))
(print (py-eval "complex(1.0, 2.0)"))
